server:
  port: 8083

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/company_auth
    username: root
    password: 8870

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shanmugakannan7549@gmail.com
    password: 8870168251Vivo   # Use your Gmail App Password here!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
